### ISSUE TITLE
Incorrect import of `antd` using `styled-components`

### ISSUE THREAD

**Issue by suevalov** [umijs/babel-plugin-import#111]
Plugin couldn't detect that imported component was used.

```js

import { Card } from 'antd';
import styled from 'styled-components';

const GroupCard = styled(Card)`
   margin-top: 10px;
   background-color: yellow;
`;

export default () => ((
   <GroupCard title='test' />
));

```

The output: 

![error](https://cloud.githubusercontent.com/assets/3672221/22141689/837202b6-def3-11e6-97bb-e6427c3f2097.png)

**Comment by suevalov** [comment]
As a temporary workaround I had to to the following:

```js
import { Card } from 'antd';
import styled from 'styled-components';

const CCard = Card;
const GroupCard = styled(CCard)`
   margin-top: 10px;
   background-color: yellow;
`;
```

**Comment by emanuel281** [comment]
This also works: 

`import { Card } from 'antd';
import styled from 'styled-components';

const GroupCard = styled(Card)`
   margin-top: 10px;
   background-color: yellow;
`;`

**Comment by paranoidjk** [comment]
This should be fixed in https://github.com/ant-design/babel-plugin-import/issues/115, can you try the latest version?
