### ISSUE TITLE
最新版插件的引入方式会报错

### ISSUE THREAD

**Issue by jensonjing** [umijs/babel-plugin-import#607]
版本号："babel-plugin-import": "1.13.4",

报错：
triggerUncaughtException(err, true /* fromPromise */);

**Comment by outNapGnaw** [comment]
why 
<img width="906" alt="image" src="https://user-images.githubusercontent.com/13870052/162663441-18270504-0b93-46ed-819a-8b2fa5923e43.png">

**Comment by shiftj18** [comment]
复议+1

```js
[BABEL]: Cannot find module '/Users/chencheng/code/github.com/umijs/babel-plugin-import/node_modules/.pnpm/babel-preset-umi@1.8.4/node_modules/@babel/runtime/helpers/interopRequireDefault'
    Require stack:
    - /Users/shiftj/.clam/@ali/clam-toolkit-rxpi/package/node_modules/_babel-plugin-import@1.13.4@babel-plugin-import/lib/index.js
```

**Comment by xqxian** [comment]
+1，麻烦尽快修复…

**Comment by CodeMonkeyLin** [comment]
+1，麻烦尽快修复…

**Comment by peakcool** [comment]
是的，我也是遇到

<img width="948" alt="image" src="https://user-images.githubusercontent.com/14804014/162676079-1ab93804-c813-4519-8ca7-b3f9779dcac7.png">

**Comment by Mr-Song9898** [comment]
复议

**Comment by wufeng87** [comment]
可以先还原到低版本先用着了 `cnpm i babel-plugin-import@1.13.3`

**Comment by MGLHF** [comment]
1.13.2和1.13.4都有这个问题，先锁版本用吧，npm i babel-plugin-import@1.13.3

**Comment by ccfnever** [comment]
建议手动把 yarn.lock 等文件里的版本锁定为 1.13.3, 默认是 1.x

PS: 大家用持续集成跑的时候需要注意：umi 脚手架创建的项目默认 .gitignore 忽略了 yarn.lock package-lock.json

**Comment by wiidede** [comment]
大佬们快修一下，项目都起不来了哈哈哈🤣

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/babel-plugin-import/issues/613。

**Comment by otakustay** [comment]
是否能用`1.13.3`发布一个`1.13.5`版本，有一些NPM源的工具无法正确地处理unpublish事件，导致最新版本依然是`1.13.4`很难回退

**Comment by thinkive** [comment]
同一个问题，多次出现。哎
