### ISSUE TITLE
1.13.4版本编译错了

### ISSUE THREAD

**Issue by 303394539** [umijs/babel-plugin-import#608]
在babel-plugin-import/lib/index.js
Users/chencheng/code/github.com/umijs/babel-plugin-import/node_modules/.pnpm/babel-preset-umi@1.8.4/node_modules/@babel/runtime/helpers/interopRequireDefault
被编译进去了

**Comment by 303394539** [comment]
@sorrycc

**Comment by peakcool** [comment]
#607

**Comment by retondong** [comment]
同样的问题在1.13.1也遇到过 当时发了patch 估计这又漏掉了 暂时把版本限制到1.13.2可以绕过这个问题

**Comment by ccfnever** [comment]
@retondong  1.13.2 貌似也不行。1.13.3 ok

建议手动把 yarn.lock 等文件里的版本锁定为 1.13.3, 默认是 1.x

PS: 大家用持续集成跑的时候需要注意：umi 脚手架创建的项目默认 .gitignore 忽略了 yarn.lock package-lock.json

**Comment by 303394539** [comment]
应该之前提交的babel方式差一些babel配置，比如configFile:false。把开发者的路径编译进去了

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/babel-plugin-import/issues/613。
