### ISSUE TITLE
QAQ编译报错了

### ISSUE THREAD

**Issue by xiaoqingb** [umijs/babel-plugin-import#609]
ERROR  Error: [BABEL]: Cannot find module '/Users/chencheng/code/github.com/umijs/babel-plugin-import/node_modules/.pnpm/babel-preset-umi@1.8.4/node_modules/@babel/runtime/helpers/interopRequireDefault'
Require stack:
- /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/babel-plugin-import/lib/index.js
- /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/@babel/core/lib/config/files/module-types.js
- /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/@babel/core/lib/config/files/configuration.js
- /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/@babel/core/lib/config/files/index.js
- /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/@babel/core/lib/index.js
- /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/@vue/cli-plugin-babel/index.js
- /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/@vue/cli-service/lib/Service.js
- /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/@vue/cli-service/bin/vue-cli-service.js (While processing: /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/babel-plugin-import/lib/index.js)
Error: [BABEL]: Cannot find module '/Users/chencheng/code/github.com/umijs/babel-plugin-import/node_modules/.pnpm/babel-preset-umi@1.8.4/node_modules/@babel/runtime/helpers/interopRequireDefault'
Require stack:
- /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/babel-plugin-import/lib/index.js
- /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/@babel/core/lib/config/files/module-types.js
- /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/@babel/core/lib/config/files/configuration.js
- /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/@babel/core/lib/config/files/index.js
- /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/@babel/core/lib/index.js
- /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/@vue/cli-plugin-babel/index.js
- /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/@vue/cli-service/lib/Service.js
- /Users/xiaoqingb/work/temp1/beacon_pagebuilder_ui/node_modules/@vue/cli-service/bin/vue-cli-service.js (While processing: /Users/xiaoqingb/work/temp1/beacon_pagebui
![image](https://user-images.githubusercontent.com/49091613/162709150-8ea2f2bb-52ea-4758-a8a4-378a371b7a7d.png)

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/babel-plugin-import/issues/613。
