### ISSUE TITLE
babel-preset-umi@1.8.4版本bug

### ISSUE THREAD

**Issue by Tigerremy** [umijs/babel-plugin-import#612]
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/29435792/162763258-3dd95ecc-6a16-4dff-968a-672a3faf0a89.png">

Error: [BABEL]: Cannot find module '/Users/chencheng/code/github.com/umijs/babel-plugin-import/node_modules/.pnpm/babel-preset-umi@1.8.4/node_modules/@babel/runtime/helpers/interopRequireDefault'

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/babel-plugin-import/issues/613。
