### ISSUE TITLE
公告：1.13.4 的问题说明

### ISSUE THREAD

**Issue by sorrycc** [umijs/babel-plugin-import#613]
介于有多个 issue，统一说明下。

1.13.4 有问题，2022.4.11 中午发现有问题时，已通过 dist-tag 设置 latest 回 1.13.3。

```bash
$ npm info babel-plugin-import
dist-tags:
beta: 1.6.3-beta.1  latest: 1.13.3
```

正常来说，npm install babel-plugin-import@^1 不会安装到错误的版本。

```bash
$ npm i babel-plugin-import@^1
Packages: +7
+++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/chencheng/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 7, reused 7, downloaded 0, added 7, done

dependencies:
+ babel-plugin-import 1.13.3
```

所以，不清楚大家怎么会安装到错误的版本。如果还有遇到，建议做两个尝试，

1、删除 node_modules（如果有 yarn.lock、package-lock.json、pnpm-lock.yarml，请一并删除）并重装
2、检查本地或 npm mirror（如有）的缓存情况

**Comment by 303394539** [comment]
很多项目可能不会粗暴的直接 ^1，或者直接1.x。
也许是大家工作比较积极，刚好在你发布以后就遇到了，就及时反馈了^-^
比如我就是用的~1.13.3，刚好中午就遇到了1.13.4的问题，然后自己锁定了1.13.3。后面你修改以后应该就好了。

**Comment by zhangyuang** [comment]
可以考虑发个1.13.5来覆盖？这样就保证不会出现问题了

**Comment by sorrycc** [comment]
cnpm 也是 1.13.3。

```bash
$ cnpm i babel-plugin-import
✔ Installed 1 packages
✔ Linked 7 latest versions
✔ Run 0 scripts
✔ All packages installed (7 packages installed from npm registry, used 290ms(network 289ms), speed 193.64KB/s, json 7(55.96KB), tarball 0B)
$ cat node_modules/babel-plugin-import/package.json
{
  "name": "babel-plugin-import",
  "version": "1.13.3",
```

**Comment by mizi-lin** [comment]
@sorrycc  

在 yarn v1.x 没有问题 安装的是 1.13.3 

<img width="384" alt="image" src="https://user-images.githubusercontent.com/2802841/162894185-67e6c32c-9d4e-4202-8b33-c0667c4796ac.png">


但在 yarn v3.x 安装的 1.13.4 

<img width="774" alt="image" src="https://user-images.githubusercontent.com/2802841/162894284-6784e0b3-2f9a-4f45-a5b9-b6fb077a1a14.png">

**Comment by 303394539** [comment]
@sorrycc 之前在用gulp打包的时候，有.babelrc之类的文件，打包的时候对于babel插件的参数，遇到过configFile参数会造成出现这种绝对路径的问题。可以检查下是否是这个原因。
![image](https://user-images.githubusercontent.com/1750965/162895423-d74cd991-9575-4627-aeb5-ff428ed49829.png)

**Comment by itzhaolin** [comment]
大佬简单粗暴了，近期项目 全部构建失败了。

**Comment by AieraFlyyyy** [comment]
兄弟们，锁1.12.0版本就可以了

**Comment by mizi-lin** [comment]
> @mizi-lin 这是有本地的缓存吧。

特意清了缓存 测试的·

**Comment by sorrycc** [comment]
@mizi-lin 全局缓存也清了？

**Comment by sorrycc** [comment]
https://github.com/umijs/babel-plugin-import/releases/tag/v1.13.5
+ 1.13.5
